spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: gauri@weetechsolution.com
    password: *********
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      security-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 600000  # for 10 minutes
      refresh-token:
        expiration: 86400000 # for a day
security:
  jwt:
    username: ceo-user
    password: ceo-password